twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        navigation_service: '@App\Application\Navigation\NavigationServiceInterface'
    form_themes: ['form/bulma_theme.html.twig']
