#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_dashboard:
  path: /
  controller: App\Infrastructure\Dashboard\Controllers\DashboardController::index
app_login:
  path: /login
  controller: App\Infrastructure\Users\Controllers\SecurityController::login
app_logout:
  path: /logout
  controller: App\Infrastructure\Users\Controllers\SecurityController::logout

users_index:
  path: /users
  controller: App\Infrastructure\Users\Controllers\UserController::index
users_create:
  path: /users/create
  controller: App\Infrastructure\Users\Controllers\UserController::create
users_view:
  path: /users/{userId}
  controller: App\Infrastructure\Users\Controllers\UserController::view
users_edit:
  path: /users/{userId}/edit
  controller: App\Infrastructure\Users\Controllers\UserController::edit
users_delete:
  path: /users/{userId}/delete
  controller: App\Infrastructure\Users\Controllers\UserController::delete
  methods: POST|DELETE

customers_index:
  path: /customers
  controller: App\Infrastructure\Customers\Controllers\CustomerController::index
customers_create:
  path: /customers/create
  controller: App\Infrastructure\Customers\Controllers\CustomerController::create
customers_view:
  path: /customers/{customerId}
  controller: App\Infrastructure\Customers\Controllers\CustomerController::view
customers_edit:
  path: /customers/{customerId}/edit
  controller: App\Infrastructure\Customers\Controllers\CustomerController::edit
customers_delete:
  path: /customers/{customerId}/delete
  controller: App\Infrastructure\Customers\Controllers\CustomerController::delete
  methods: POST|DELETE

campaigns_index:
  path: /campaigns
  controller: App\Infrastructure\Campaigns\Controllers\CampaignController::index
campaigns_create:
  path: /campaigns/create
  controller: App\Infrastructure\Campaigns\Controllers\CampaignController::create
campaigns_view:
  path: /campaigns/{campaignId}
  controller: App\Infrastructure\Campaigns\Controllers\CampaignController::view
campaigns_edit:
  path: /campaigns/{campaignId}/edit
  controller: App\Infrastructure\Campaigns\Controllers\CampaignController::edit
campaigns_delete:
  path: /campaigns/{campaignId}/delete
  controller: App\Infrastructure\Campaigns\Controllers\CampaignController::delete
  methods: POST|DELETE
